const MAX_HAND_SIZE = 5;
const ENERGY_PER_TURN = 3;
const STARTER_CARDS = [
{id:"atk3",name:"Dano Básico 3",type:"Ataque",rarity:"inicial",cost:1,copies:1,desc:"Causa 3 de dano.",effects:[{kind:"damage",value:3}]},
{id:"atk5",name:"Dano Básico 5",type:"Ataque",rarity:"inicial",cost:1,copies:1,desc:"Causa 5 de dano.",effects:[{kind:"damage",value:5}]},
{id:"heal5",name:"+5 HP",type:"Suporte",rarity:"inicial",cost:1,copies:1,desc:"Recupera 5 HP.",effects:[{kind:"heal",value:5}]},
{id:"block4",name:"Block 4",type:"Defesa",rarity:"inicial",cost:1,copies:1,desc:"Bloqueia 4 de dano.",effects:[{kind:"block",value:4}]},
{id:"poison1",name:"Veneno -1",type:"Debuff",rarity:"inicial",cost:2,copies:1,desc:"4 dano + veneno 1.",effects:[{kind:"damage",value:4},{kind:"poison",value:1}]},
{id:"vamp3",name:"Vampiro 3",type:"Ataque",rarity:"inicial",cost:2,copies:1,desc:"3 dano e cura 3.",effects:[{kind:"lifesteal",damage:3,heal:3}]},
{id:"buff2",name:"Buff ATK 2",type:"Buff",rarity:"inicial",cost:1,copies:1,desc:"+2 no dano dos seus ataques.",effects:[{kind:"buffatk",value:2}]},
{id:"curse2",name:"Maldição 2",type:"Debuff",rarity:"inicial",cost:1,copies:1,desc:"Inimigo perde 2 de ataque.",effects:[{kind:"curse",value:2}]},
{id:"imm1",name:"Imortal 1",type:"Buff",rarity:"inicial",cost:1,copies:1,desc:"Ganha 1 HP por turno.",effects:[{kind:"regen",value:1}]},
{id:"reb2",name:"Rebote 2",type:"Buff",rarity:"inicial",cost:1,copies:1,desc:"Reflete 2 de dano ao sofrer ataque.",effects:[{kind:"rebote",value:2}]}
];
const LEVEL_POOL = [
{id:"heal10",name:"+10 HP",type:"Suporte",rarity:"media",cost:2,copies:2,desc:"Recupera 10 HP.",effects:[{kind:"heal",value:10}],stage:"early",weight:4},
{id:"heal15",name:"+15 HP",type:"Suporte",rarity:"media",cost:3,copies:2,desc:"Recupera 15 HP.",effects:[{kind:"heal",value:15}],stage:"mid",weight:3},
{id:"heal20",name:"+20 HP",type:"Suporte",rarity:"dificil",cost:3,copies:1,desc:"Recupera 20 HP.",effects:[{kind:"heal",value:20}],stage:"late",weight:2},
{id:"atk8",name:"Dano 8",type:"Ataque",rarity:"media",cost:2,copies:2,desc:"Causa 8 de dano.",effects:[{kind:"damage",value:8}],stage:"early",weight:4},
{id:"atk10",name:"Dano 10",type:"Ataque",rarity:"media",cost:3,copies:2,desc:"Causa 10 de dano.",effects:[{kind:"damage",value:10}],stage:"mid",weight:4},
{id:"atk15",name:"Dano 15",type:"Ataque",rarity:"dificil",cost:3,copies:1,desc:"Causa 15 de dano.",effects:[{kind:"damage",value:15}],stage:"late",weight:3},
{id:"atk20",name:"Dano 20",type:"Ataque",rarity:"dificil",cost:3,copies:1,desc:"Causa 20 de dano.",effects:[{kind:"damage",value:20}],stage:"late",weight:2},
{id:"poison3",name:"Veneno -3",type:"Debuff",rarity:"media",cost:3,copies:2,desc:"5 dano + veneno 3.",effects:[{kind:"damage",value:5},{kind:"poison",value:3}],stage:"early",weight:3},
{id:"poison5",name:"Veneno -5",type:"Debuff",rarity:"dificil",cost:3,copies:1,desc:"8 dano + veneno 5.",effects:[{kind:"damage",value:8},{kind:"poison",value:5}],stage:"late",weight:2},
{id:"vamp5",name:"Vampiro 5",type:"Ataque",rarity:"media",cost:2,copies:2,desc:"5 dano e cura 5.",effects:[{kind:"lifesteal",damage:5,heal:5}],stage:"early",weight:3},
{id:"vamp8",name:"Vampiro 8",type:"Ataque",rarity:"dificil",cost:3,copies:1,desc:"8 dano e cura 8.",effects:[{kind:"lifesteal",damage:8,heal:8}],stage:"late",weight:2},
{id:"block7",name:"Block 7",type:"Defesa",rarity:"media",cost:1,copies:2,desc:"Bloqueia 7 de dano.",effects:[{kind:"block",value:7}],stage:"early",weight:4},
{id:"block10",name:"Block 10",type:"Defesa",rarity:"media",cost:2,copies:2,desc:"Bloqueia 10 de dano.",effects:[{kind:"block",value:10}],stage:"mid",weight:3},
{id:"blockall",name:"Block Total",type:"Defesa",rarity:"dificil",cost:3,copies:1,desc:"Bloqueia totalmente o próximo dano.",effects:[{kind:"blockall"}],stage:"late",weight:2},
{id:"buff3",name:"Buff ATK 3",type:"Buff",rarity:"media",cost:2,copies:2,desc:"+3 no dano dos seus ataques.",effects:[{kind:"buffatk",value:3}],stage:"early",weight:3},
{id:"buff5",name:"Buff ATK 5",type:"Buff",rarity:"dificil",cost:3,copies:1,desc:"+5 no dano dos seus ataques.",effects:[{kind:"buffatk",value:5}],stage:"late",weight:2},
{id:"curse3",name:"Maldição 3",type:"Debuff",rarity:"media",cost:2,copies:2,desc:"Inimigo perde 3 de ataque.",effects:[{kind:"curse",value:3}],stage:"early",weight:3},
{id:"curse5",name:"Maldição 5",type:"Debuff",rarity:"dificil",cost:3,copies:1,desc:"Inimigo perde 5 de ataque.",effects:[{kind:"curse",value:5}],stage:"late",weight:2},
{id:"imm3",name:"Imortal 3",type:"Buff",rarity:"media",cost:2,copies:2,desc:"Ganha 3 HP por turno.",effects:[{kind:"regen",value:3}],stage:"mid",weight:3},
{id:"imm5",name:"Imortal 5",type:"Buff",rarity:"media",cost:3,copies:2,desc:"Ganha 5 HP por turno.",effects:[{kind:"regen",value:5}],stage:"late",weight:2},
{id:"reb3",name:"Rebote 3",type:"Buff",rarity:"media",cost:2,copies:2,desc:"Reflete 3 de dano.",effects:[{kind:"rebote",value:3}],stage:"mid",weight:3},
{id:"reb5",name:"Rebote 5",type:"Buff",rarity:"media",cost:3,copies:2,desc:"Reflete 5 de dano.",effects:[{kind:"rebote",value:5}],stage:"late",weight:2},
{id:"rebmaster",name:"Rebote Master",type:"Buff",rarity:"dificil",cost:3,copies:1,desc:"Na próxima vez que sofrer ataque, devolve 10 de dano.",effects:[{kind:"reboteonce",value:10}],stage:"late",weight:1},
{id:"curepoison",name:"Cura do Veneno",type:"Suporte",rarity:"media",cost:1,copies:2,desc:"Remove veneno de si.",effects:[{kind:"cleanse",targetEffect:"poison"}],stage:"early",weight:3},
{id:"forcedheal",name:"Cura Forçada",type:"Suporte",rarity:"dificil",cost:2,copies:1,desc:"Remove Imortal do inimigo.",effects:[{kind:"removeEnemyEffect",targetEffect:"regen"}],stage:"late",weight:2},
{id:"exorcism",name:"Exorcismo",type:"Suporte",rarity:"media",cost:2,copies:2,desc:"Remove Imortal do inimigo.",effects:[{kind:"removeEnemyEffect",targetEffect:"regen"}],stage:"mid",weight:2},
{id:"nerfar",name:"Nerfar",type:"Suporte",rarity:"media",cost:2,copies:2,desc:"Remove Rebote do inimigo.",effects:[{kind:"removeEnemyEffect",targetEffect:"rebote"}],stage:"mid",weight:2},
{id:"rezet",name:"Rezet",type:"Suporte",rarity:"media",cost:2,copies:2,desc:"Remove Buff ATK do inimigo.",effects:[{kind:"removeEnemyEffect",targetEffect:"buffatk"}],stage:"mid",weight:2},
{id:"revitalize",name:"Revitalizar",type:"Suporte",rarity:"media",cost:1,copies:2,desc:"Remove maldição em si próprio.",effects:[{kind:"cleanse",targetEffect:"curse"}],stage:"mid",weight:2},
{id:"defense1",name:"Defesa",type:"Defesa",rarity:"dificil",cost:3,copies:1,desc:"Bloqueia todas as ações do inimigo por 1 turno.",effects:[{kind:"stunTurns",value:1}],stage:"mid",weight:2},
{id:"defense2",name:"Defesa 2",type:"Defesa",rarity:"dificil",cost:3,copies:1,desc:"Bloqueia todas as ações do inimigo por 2 turnos.",effects:[{kind:"stunTurns",value:2}],stage:"late",weight:1},
{id:"discard1",name:"Descarte 1",type:"Debuff",rarity:"media",cost:2,copies:2,desc:"Inimigo descarta 1 carta da mão.",effects:[{kind:"discardEnemy",value:1}],stage:"mid",weight:2},
{id:"discard2",name:"Descarte 2",type:"Debuff",rarity:"media",cost:3,copies:2,desc:"Inimigo descarta 2 cartas da mão.",effects:[{kind:"discardEnemy",value:2}],stage:"late",weight:2},
{id:"chaos2",name:"Caos 2",type:"Debuff",rarity:"media",cost:2,copies:2,desc:"Inimigo descarta 2 cartas e recebe 2 aleatórias.",effects:[{kind:"chaosEnemy",value:2}],stage:"mid",weight:2},
{id:"chaos3",name:"Caos 3",type:"Debuff",rarity:"dificil",cost:3,copies:1,desc:"Inimigo descarta 3 cartas e recebe 3 aleatórias.",effects:[{kind:"chaosEnemy",value:3}],stage:"late",weight:1},
{id:"fullchaos",name:"Completo Caos",type:"Debuff",rarity:"dificil",cost:3,copies:1,desc:"Troca toda a mão entre os jogadores.",effects:[{kind:"swapHands"}],stage:"late",weight:1},
{id:"troco",name:"Troco",type:"Debuff",rarity:"dificil",cost:2,copies:1,desc:"Devolve exatamente o último ataque sofrido.",effects:[{kind:"troco"}],stage:"mid",weight:2},
{id:"troca",name:"Troca",type:"Debuff",rarity:"dificil",cost:3,copies:1,desc:"Rouba uma carta aleatória da mão do inimigo e dá uma sua em troca.",effects:[{kind:"tradeCard"}],stage:"late",weight:1},
{id:"sacrifice1",name:"Sacrifício",type:"Ataque",rarity:"dificil",cost:3,copies:1,desc:"Perde 4 HP e causa 18 dano.",effects:[{kind:"selfdamage",value:4},{kind:"damage",value:18}],stage:"late",weight:1},
{id:"sacrifice2",name:"Sacrifício 2",type:"Ataque",rarity:"dificil",cost:3,copies:1,desc:"Perde 6 HP e causa 22 dano.",effects:[{kind:"selfdamage",value:6},{kind:"damage",value:22}],stage:"late",weight:1},
{id:"metamorph",name:"Metamorfosis",type:"Especial",rarity:"dificil",cost:2,copies:1,desc:"Copia o efeito de outra carta da sua mão.",effects:[{kind:"metamorph"}],stage:"late",weight:1},
{id:"combo",name:"Combo",type:"Especial",rarity:"dificil",cost:2,copies:1,desc:"No próximo turno, ganha energia extra.",effects:[{kind:"combo"}],stage:"late",weight:1}
];
const ALL_CARDS = [...STARTER_CARDS, ...LEVEL_POOL];
function getCard(cardId){ return ALL_CARDS.find(c => c.id === cardId) || null; }
