const SAVE_KEY="way_ly_game_split_v1";let gameState={save:loadSave(),battle:null};
function el(id){return document.getElementById(id)}
function defaultSave(){return{level:START_LEVEL,wins:0,losses:0,options:{music:60,sfx:70}}}
function loadSave(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return defaultSave();const parsed=JSON.parse(raw);return{...defaultSave(),...parsed,level:clampLevel(parsed.level??START_LEVEL),options:{...defaultSave().options,...(parsed.options||{})}}}catch(e){return defaultSave()}}
function saveSave(){localStorage.setItem(SAVE_KEY,JSON.stringify(gameState.save));renderMenuStats()}
function clearDebug(){const box=el("debugBox");if(box){box.style.display="none";box.textContent=""}}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));el(id).classList.add("active")}
function goMenu(){renderMenuStats();showScreen("menu")}
function openDeck(){renderDeck();showScreen("deck")}
function openOptions(){el("musicRange").value=gameState.save.options.music;el("sfxRange").value=gameState.save.options.sfx;el("optionsModal").classList.add("show")}
function closeOptions(){el("optionsModal").classList.remove("show")}
function saveOptions(){gameState.save.options.music=Number(el("musicRange").value);gameState.save.options.sfx=Number(el("sfxRange").value);saveSave();closeOptions();alert("Opções salvas.")}
function exitGame(){alert("Para sair, feche a aba do navegador.")}
function shuffle(arr){const copy=arr.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function createEntity(name,maxHp,deck){return{name,maxHp,hp:maxHp,deck:shuffle(deck),hand:[],discard:[],effects:[]}}
function addLog(text){const log=el("battleLog");const div=document.createElement("div");div.textContent=text;log.appendChild(div);log.scrollTop=log.scrollHeight}
function renderMenuStats(){el("statUnlocked").textContent=getUnlockedCards(gameState.save.level).length;el("statDeckSize").textContent=buildDeckFromUnlocked(gameState.save.level).length;el("statMaxHand").textContent=MAX_HAND_SIZE;el("statLevel").textContent=gameState.save.level;el("statWins").textContent=gameState.save.wins;el("statLosses").textContent=gameState.save.losses}
function renderDeck(){const grid=el("deckGrid");grid.innerHTML="";const unlocked=new Set(getUnlockedCards(gameState.save.level));el("deckCount").textContent=buildDeckFromUnlocked(gameState.save.level).length;el("deckLevel").textContent=gameState.save.level;CARDS.forEach(card=>{const isUnlocked=unlocked.has(card.id);const cardDiv=document.createElement("div");cardDiv.className="deck-card"+(isUnlocked?"":" locked");cardDiv.innerHTML=`<strong>${card.name}</strong><div class="small">${card.desc}</div><div class="small" style="margin-top:6px;">Tipo: ${card.type}</div><div class="small">Raridade: ${card.rarity}</div><div class="small">Cópias no deck: ${card.copies}</div><div class="small">${isUnlocked?"Liberada":"Bloqueada"}</div>`;grid.appendChild(cardDiv)})}
function drawCard(entity,amount=1){for(let i=0;i<amount;i++){if(entity.deck.length===0){if(entity.discard.length>0){entity.deck=shuffle(entity.discard);entity.discard=[]}else{return}}const drawnCard=entity.deck.pop();if(entity.hand.length>=MAX_HAND_SIZE){entity.discard.push(drawnCard);addLog(entity.name+" comprou uma carta, mas a mão estava cheia. A carta foi para o descarte.");continue}entity.hand.push(drawnCard)}}
function getEffect(entity,id){return entity.effects.find(effect=>effect.id===id&&effect.duration>0)||null}
function removeEffect(entity,id){entity.effects=entity.effects.filter(effect=>effect.id!==id)}
function tickEffects(entity){const poison=getEffect(entity,"poison");if(poison){entity.hp=Math.max(0,entity.hp-(poison.value||2));addLog(entity.name+" sofreu "+(poison.value||2)+" de dano de veneno.")}entity.effects.forEach(effect=>{if(effect.duration>0)effect.duration-=1});entity.effects=entity.effects.filter(effect=>effect.duration>0&&(effect.id!=="block"||effect.value>0))}
function spendBlock(entity,amount){const block=getEffect(entity,"block");if(!block)return amount;const absorbed=Math.min(block.value,amount);block.value-=absorbed;if(block.value<=0)block.duration=0;addLog(entity.name+" bloqueou "+absorbed+" de dano.");return amount-absorbed}
function applyEffect(effect,source,target){switch(effect.kind){case"damage":{let damage=effect.value;if(effect.tag==="normal"&&getEffect(target,"curse"))damage+=3;damage=spendBlock(target,damage);target.hp=Math.max(0,target.hp-damage);addLog(source.name+" causou "+damage+" de dano.");break}case"heal":source.hp=Math.min(source.maxHp,source.hp+effect.value);addLog(source.name+" recuperou "+effect.value+" HP.");break;case"block":{const existing=getEffect(source,"block");if(existing){existing.value+=effect.value;existing.duration=Math.max(existing.duration,effect.duration||1)}else{source.effects.push({id:"block",value:effect.value,duration:effect.duration||1})}addLog(source.name+" ganhou "+effect.value+" de bloqueio.");break}case"status":{const existing=getEffect(target,effect.id);if(existing){existing.duration=Math.max(existing.duration,effect.duration||1);if(effect.value!=null)existing.value=effect.value}else{target.effects.push({id:effect.id,duration:effect.duration||1,value:effect.value})}addLog(target.name+" recebeu status: "+effect.id+".");break}case"lifesteal":{let damage=effect.damage;damage=spendBlock(target,damage);target.hp=Math.max(0,target.hp-damage);source.hp=Math.min(source.maxHp,source.hp+effect.heal);addLog(source.name+" causou "+damage+" e recuperou "+effect.heal+" HP.");break}case"draw":drawCard(source,effect.value);addLog(source.name+" tentou comprar "+effect.value+" carta(s).");break;case"cleanse":removeEffect(source,effect.id);addLog(source.name+" removeu o efeito "+effect.id+".");break;case"remove_block":removeEffect(target,"block");addLog(target.name+" perdeu o bloqueio.");break}}
function resolveCard(card,source,target){addLog(source.name+" usou "+card.name+".");card.effects.forEach(effect=>applyEffect(effect,source,target))}
function afterActionDraw(){drawCard(gameState.battle.player,1);drawCard(gameState.battle.enemy,1);addLog("Ambos tentaram comprar 1 carta.")}
function renderEffectList(targetId,entity){const wrap=el(targetId);wrap.innerHTML="";const active=entity.effects.filter(effect=>effect.duration>0);if(active.length===0){const chip=document.createElement("div");chip.className="effect-chip";chip.textContent="Sem efeitos";wrap.appendChild(chip);return}active.forEach(effect=>{const chip=document.createElement("div");chip.className="effect-chip";if(effect.id==="block")chip.textContent="Block "+effect.value+" ("+effect.duration+")";else if(effect.id==="curse")chip.textContent="Curse ("+effect.duration+")";else if(effect.id==="poison")chip.textContent="Poison "+(effect.value||2)+" ("+effect.duration+")";else if(effect.id==="stun")chip.textContent="Stun ("+effect.duration+")";else chip.textContent=effect.id+" ("+effect.duration+")";wrap.appendChild(chip)})}
function renderBattle(){const b=gameState.battle;if(!b)return;el("turnText").textContent="Turno: "+(b.turn==="player"?"Player":b.enemy.name);el("playerHpText").textContent=b.player.hp;el("playerMaxHpText").textContent=b.player.maxHp;el("enemyHpText").textContent=b.enemy.hp;el("enemyMaxHpText").textContent=b.enemy.maxHp;el("enemyName").textContent=b.enemy.name;el("playerHpBar").style.width=((b.player.hp/b.player.maxHp)*100)+"%";el("enemyHpBar").style.width=((b.enemy.hp/b.enemy.maxHp)*100)+"%";el("playerHandCount").textContent=b.player.hand.length;el("enemyHandCount").textContent=b.enemy.hand.length;el("playerDeckCount").textContent=b.player.deck.length;el("enemyDeckCount").textContent=b.enemy.deck.length;renderEffectList("playerEffects",b.player);renderEffectList("enemyEffects",b.enemy);renderHand()}
function renderHand(){const b=gameState.battle;const hand=el("hand");hand.innerHTML="";if(!b)return;const canPlay=b.turn==="player"&&!b.locked&&b.playerCanAct;if(b.player.hand.length===0){hand.innerHTML="<div class='small'>Sem cartas na mão.</div>";return}b.player.hand.forEach((cardId,index)=>{const card=getCard(cardId);if(!card)return;const cardEl=document.createElement("div");cardEl.className="card"+(canPlay?"":" disabled");cardEl.innerHTML=`<div class="card-type">${card.type}</div><div class="card-name">${card.name}</div><div class="card-desc">${card.desc}</div><div class="card-foot"><span>${card.target==="enemy"?"Alvo: Inimigo":"Alvo: Você"}</span><span>${card.rarity}</span></div>`;cardEl.onclick=function(){if(!canPlay)return;playPlayerCard(index)};hand.appendChild(cardEl)})}
function startBattle(){const level=gameState.save.level;const enemyTemplate=getEnemyTemplateForLevel(level);const hpBonus=getCurrentHpBonus(level);const playerDeck=buildDeckFromUnlocked(level);const enemyDeck=buildEnemyDeck(level);const equalHp=BASE_PLAYER_HP+hpBonus;gameState.battle={turn:"player",locked:false,playerCanAct:true,player:createEntity("Player",equalHp,playerDeck),enemy:createEntity(enemyTemplate.name,equalHp,enemyDeck)};drawCard(gameState.battle.player,5);drawCard(gameState.battle.enemy,5);el("battleLog").innerHTML="";addLog("Batalha iniciada.");addLog("Regra ativa: 1 carta por turno. Após cada ação, ambos compram 1 carta.");addLog("Limite máximo de mão: "+MAX_HAND_SIZE+" cartas.");renderBattle();showScreen("battle")}
function playPlayerCard(handIndex){const b=gameState.battle;if(!b||b.turn!=="player"||b.locked||!b.playerCanAct)return;const cardId=b.player.hand[handIndex];const card=getCard(cardId);if(!card)return;b.playerCanAct=false;b.player.hand.splice(handIndex,1);b.player.discard.push(cardId);const target=card.target==="enemy"?b.enemy:b.player;resolveCard(card,b.player,target);if(checkBattleEnd())return;afterActionDraw();b.turn="enemy";renderBattle();setTimeout(runEnemyTurn,700)}
function chooseEnemyCardIndex(){const b=gameState.battle;if(!b||b.enemy.hand.length===0)return-1;if(getEffect(b.enemy,"stun"))return-1;if(b.enemy.hp<=Math.floor(b.enemy.maxHp*0.35)){const healIndex=b.enemy.hand.findIndex(cardId=>{const c=getCard(cardId);return c&&c.effects.some(effect=>effect.kind==="heal")});if(healIndex>=0)return healIndex}if(!getEffect(b.player,"curse")){const curseIndex=b.enemy.hand.findIndex(cardId=>{const c=getCard(cardId);return c&&c.effects.some(effect=>effect.kind==="status"&&effect.id==="curse")});if(curseIndex>=0)return curseIndex}let bestIndex=0;let bestScore=-1;b.enemy.hand.forEach((cardId,index)=>{const c=getCard(cardId);if(!c)return;let score=0;c.effects.forEach(effect=>{if(effect.kind==="damage")score+=effect.value;if(effect.kind==="lifesteal")score+=effect.damage;if(effect.kind==="heal")score+=2;if(effect.kind==="status")score+=3;if(effect.kind==="draw")score+=1});if(score>bestScore){bestScore=score;bestIndex=index}});return bestIndex}
function runEnemyTurn(){const b=gameState.battle;if(!b)return;b.locked=true;if(getEffect(b.enemy,"stun")){addLog(b.enemy.name+" está atordoado e perdeu o turno.");removeEffect(b.enemy,"stun")}else{const index=chooseEnemyCardIndex();if(index>=0){const cardId=b.enemy.hand[index];const card=getCard(cardId);b.enemy.hand.splice(index,1);b.enemy.discard.push(cardId);const target=card.target==="enemy"?b.player:b.enemy;resolveCard(card,b.enemy,target)}else addLog(b.enemy.name+" passou o turno.")}if(checkBattleEnd())return;afterActionDraw();tickEffects(b.player);tickEffects(b.enemy);b.turn="player";b.playerCanAct=true;b.locked=false;addLog("Seu turno.");renderBattle()}
function checkBattleEnd(){const b=gameState.battle;if(!b)return false;if(b.enemy.hp<=0){finishBattle(true);return true}if(b.player.hp<=0){finishBattle(false);return true}return false}
function finishBattle(win){const previousLevel=gameState.save.level;if(win){gameState.save.wins+=1;if(gameState.save.level<MAX_LEVEL)gameState.save.level+=1}else gameState.save.losses+=1;saveSave();const oldUnlocked=getUnlockedCards(previousLevel);const newUnlocked=getUnlockedCards(gameState.save.level);const newCards=newUnlocked.filter(id=>!oldUnlocked.includes(id));el("resultTitle").textContent=win?"Vitória":"Derrota";el("resultText").textContent=win?(gameState.save.level>=MAX_LEVEL?"Você venceu e chegou ao nível máximo.":"Você venceu e subiu de nível."):"Você perdeu. Ajuste sua estratégia e tente novamente.";el("resultStats").innerHTML=`<div class="row"><span>Nível atual</span><strong>${gameState.save.level}</strong></div><div class="row"><span>Cartas desbloqueadas</span><strong>${getUnlockedCards(gameState.save.level).length}</strong></div><div class="row"><span>Cartas ativas no deck</span><strong>${buildDeckFromUnlocked(gameState.save.level).length}</strong></div><div class="row"><span>HP base atual</span><strong>${BASE_PLAYER_HP+getCurrentHpBonus(gameState.save.level)}</strong></div><div class="row"><span>Vitórias / Derrotas</span><strong>${gameState.save.wins} / ${gameState.save.losses}</strong></div><div class="row"><span>Nova carta liberada</span><strong>${newCards.length?newCards.map(id=>getCard(id).name).join(", "):"Nenhuma"}</strong></div>${win&&gameState.save.level<MAX_LEVEL?'<button class="btn-main" onclick="startBattle()">Próximo nível</button>':''}`;renderMenuStats();showScreen("result")}
function concedeBattle(){if(!gameState.battle)return;gameState.battle.player.hp=0;checkBattleEnd()}
function resetSave(){const ok=confirm("Apagar todo o save?");if(!ok)return;gameState.save=defaultSave();saveSave();closeOptions();goMenu();alert("Save resetado.")}
window.startBattle=startBattle;window.openDeck=openDeck;window.openOptions=openOptions;window.closeOptions=closeOptions;window.saveOptions=saveOptions;window.exitGame=exitGame;window.goMenu=goMenu;window.concedeBattle=concedeBattle;window.resetSave=resetSave;clearDebug();renderMenuStats();
